In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.3.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np
print(np.__version__)


1.26.0


In [2]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
import numpy as np
arr = np.array([[1,2,3,5,6],[6,8,9,10,11]])
d = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])
print(arr)
print(arr.ndim)
print(d)
print(d.ndim)

[[ 1  2  3  5  6]
 [ 6  8  9 10 11]]
2
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


In [9]:
li = [1, 2, 3, 4]  
print(np.array(li)) 

[1 2 3 4]


In [10]:
list_1 = [1, 2, 3, 4] 
list_2 = [5, 6, 7, 8] 
list_3 = [9, 10, 11, 12] 
print(np.array([list_1, list_2, list_3])) 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
print(np.arange(1, 10)) 

[1 2 3 4 5 6 7 8 9]


In [12]:
print(np.linspace(1, 10, 3)) 

[ 1.   5.5 10. ]


In [13]:
print(np.zeros(5, dtype=int)) 

[0 0 0 0 0]


In [17]:
print(np.random.rand(5)) 

[0.71552569 0.92769608 0.74690242 0.74747579 0.95211345]


In [18]:
arr = np.asarray([1, 2, 3, 4]) 
# check size of the array 
print("Size:", arr.size) 
  
# check len of the array 
print("len:", len(arr)) 
  
# check shape of the array 
print("Shape:", arr.shape) 
  
# check dtype of the array elements 
print("Datatype:", arr.dtype) 
  
# change the dtype to 'float64' 
arr = arr.astype('float64') 
print(arr) 
print("Datatype:", arr.dtype)

Size: 4
len: 4
Shape: (4,)
Datatype: int32
[1. 2. 3. 4.]
Datatype: float64


In [19]:
# the array is saved in the file geekfile.npy 
np.save("geekfile", np.arange(10)) 
  
# the array is loaded into b 
print(np.load("geekfile.npy"))

[0 1 2 3 4 5 6 7 8 9]


In [20]:
x = np.arange(0, 10, 1) 
print(x) 
  
# X array saved in geekfile.txt 
c = np.savetxt("geekfile.txt", x, delimiter =', ')

[0 1 2 3 4 5 6 7 8 9]


In [22]:
Data = np.genfromtxt("data.csv", delimiter=",") 
print(Data)

[[nan nan nan]
 [ 1. nan nan]
 [ 2. nan nan]
 [ 3. nan nan]]


In [24]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
np.mean(arr)

[1 2 3 4 5]
<class 'numpy.ndarray'>


3.0

In [25]:
np.var(arr, dtype = np.float32)

2.0

In [26]:
np.std(arr, dtype = np.float32)

1.4142135