In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.3.1 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np
print(np.__version__)


1.26.0


In [2]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
import numpy as np
arr = np.array([[1,2,3,5,6],[6,8,9,10,11]])
d = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])
print(arr)
print(arr.ndim)
print(d)
print(d.ndim)

[[ 1  2  3  5  6]
 [ 6  8  9 10 11]]
2
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


In [9]:
li = [1, 2, 3, 4]  
print(np.array(li)) 

[1 2 3 4]


In [10]:
list_1 = [1, 2, 3, 4] 
list_2 = [5, 6, 7, 8] 
list_3 = [9, 10, 11, 12] 
print(np.array([list_1, list_2, list_3])) 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
print(np.arange(1, 10)) 

[1 2 3 4 5 6 7 8 9]


In [12]:
print(np.linspace(1, 10, 3)) 

[ 1.   5.5 10. ]


In [13]:
print(np.zeros(5, dtype=int)) 

[0 0 0 0 0]


In [17]:
print(np.random.rand(5)) 

[0.71552569 0.92769608 0.74690242 0.74747579 0.95211345]


In [18]:
arr = np.asarray([1, 2, 3, 4]) 
# check size of the array 
print("Size:", arr.size) 
  
# check len of the array 
print("len:", len(arr)) 
  
# check shape of the array 
print("Shape:", arr.shape) 
  
# check dtype of the array elements 
print("Datatype:", arr.dtype) 
  
# change the dtype to 'float64' 
arr = arr.astype('float64') 
print(arr) 
print("Datatype:", arr.dtype)

Size: 4
len: 4
Shape: (4,)
Datatype: int32
[1. 2. 3. 4.]
Datatype: float64


In [19]:
# the array is saved in the file geekfile.npy 
np.save("geekfile", np.arange(10)) 
  
# the array is loaded into b 
print(np.load("geekfile.npy"))

[0 1 2 3 4 5 6 7 8 9]


In [20]:
x = np.arange(0, 10, 1) 
print(x) 
  
# X array saved in geekfile.txt 
c = np.savetxt("geekfile.txt", x, delimiter =', ')

[0 1 2 3 4 5 6 7 8 9]


In [22]:
Data = np.genfromtxt("data.csv", delimiter=",") 
print(Data)

[[nan nan nan]
 [ 1. nan nan]
 [ 2. nan nan]
 [ 3. nan nan]]


In [24]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))
np.mean(arr)

[1 2 3 4 5]
<class 'numpy.ndarray'>


3.0

In [25]:
np.var(arr, dtype = np.float32)

2.0

In [26]:
np.std(arr, dtype = np.float32)

1.4142135

In [2]:
import numpy as np
# create a NumPy array using numpy.arange() 
print(np.arange(1, 10)) 
  
# create a NumPy array using numpy.linspace() 
print(np.linspace(1, 10, 3)) 
  
# create a NumPy array using numpy.zeros() 
print(np.zeros(5, dtype=int)) 
  
# create a NumPy array using numpy.ones() 
print(np.ones(5, dtype=int)) 
  
# create a NumPy array using numpy.random.rand() 
print(np.random.rand(5)) 
  
# create a NumPy array using numpy.random.randint() 
print(np.random.randint(5, size=10)) 

[1 2 3 4 5 6 7 8 9]
[ 1.   5.5 10. ]
[0 0 0 0 0]
[1 1 1 1 1]
[0.20891537 0.16307301 0.66980091 0.68797965 0.2698585 ]
[4 4 3 4 3 3 3 4 3 0]


In [3]:
# create a NumPy array using numpy.zeros() 
print(np.zeros([4, 3], dtype = np.int32)) 
  
# create a NumPy array using numpy.ones() 
print(np.ones([4, 3], dtype = np.int32)) 
  
# create a NumPy array using numpy.full() 
print(np.full([2, 2], 67, dtype = int)) 
  
# create a NumPy array using numpy.eye() 
print(np.eye(4))

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
[[67 67]
 [67 67]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [4]:
arr = np.asarray([1, 2, 3, 4]) 
# check size of the array 
print("Size:", arr.size) 
  
# check len of the array 
print("len:", len(arr)) 
  
# check shape of the array 
print("Shape:", arr.shape) 
  
# check dtype of the array elements 
print("Datatype:", arr.dtype) 
  
# change the dtype to 'float64' 
arr = arr.astype('float64') 
print(arr) 
print("Datatype:", arr.dtype) 
  
# convert array to list 
lis = arr.tolist() 
print("\nList:", lis) 
print(type(lis))

Size: 4
len: 4
Shape: (4,)
Datatype: int32
[1. 2. 3. 4.]
Datatype: float64

List: [1.0, 2.0, 3.0, 4.0]
<class 'list'>


In [8]:
# sorting a one dimensional 
# numpy array using numpy.sort() 
a = np.array([12, 15, 10, 1]) 
b= np.array(['Orange','Banana','mango','gava'])
print("Array before sorting",a) 
a.sort() 
print("Array after sorting",a)

print("Array before sorting",b) 
b.sort() 
print("Array after sorting",b)

Array before sorting [12 15 10  1]
Array after sorting [ 1 10 12 15]
Array before sorting ['Orange' 'Banana' 'mango' 'gava']
Array after sorting ['Banana' 'Orange' 'gava' 'mango']


In [9]:
# sorting a two dimensional 
# numpy array using numpy.sort() 
# sort along the first axis 
a = np.array([[12, 15], [10, 1]]) 
arr1 = np.sort(a, axis = 0)     
print ("Along first axis : \n", arr1)     
  
# sort along the last axis 
a = np.array([[10, 15], [12, 1]]) 
arr2 = np.sort(a, axis = -1)     
print ("\nAlong Last axis : \n", arr2) 
  
a = np.array([[12, 15], [10, 1]]) 
arr1 = np.sort(a, axis = None)     
print ("\nAlong none axis : \n", arr1)

Along first axis : 
 [[10  1]
 [12 15]]

Along Last axis : 
 [[10 15]
 [ 1 12]]

Along none axis : 
 [ 1 10 12 15]


In [12]:
# Adding the values at the end 
# of a numpy array 
rr = np.asarray([1, 2, 3, 4]) 
print("Original Array:", arr) 
  
# appending to the array 
arr = np.append(arr, [8]) 
print("Array after appending:", arr)

Original Array: [1. 2. 3. 4. 7. 7.]
Array after appending: [1. 2. 3. 4. 7. 7. 8.]


In [16]:
# Adding the values at the end 
# of a numpy array 
arr = np.arange(1, 13).reshape(2, 6) 
print("Original Array") 
print(arr, "\n") 

Original Array
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] 



In [19]:
# create another array which is 
# to be appended column-wise 
col = np.arange(5, 11).reshape(1, 6) 
arr_col = np.append(arr, col, axis=0) 
print("Array after appending the values column wise") 
print(arr_col, "\n") 

Array after appending the values column wise
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [ 5  6  7  8  9 10]] 



In [22]:
# create an array which is 
# to be appended row wise 
row = np.array([2, 3]).reshape(2, 1) 
arr_row = np.append(arr, row, axis=1) 
print("Array after appending the values row wise") 
print(arr_row)

Array after appending the values row wise
[[ 1  2  3  4  5  6  2]
 [ 7  8  9 10 11 12  3]]


In [28]:
arr = np.asarray([1, 4, 3, 5,9]) 
# Python Program illustrating numpy.insert() 
print("1D arr:", arr) 
print("Shape:", arr.shape) 
  
# Inserting value 9 at index 1 
a = np.insert(arr, 1, 9) 
print("\nArray after insertion:", a) 
print("Shape:", a.shape)

1D arr: [1 4 3 5 9]
Shape: (5,)

Array after insertion: [1 9 4 3 5 9]
Shape: (6,)


In [29]:
# Python Program illustrating 
# numpy.delete() 

arr = np.asarray([1,2,3,4,5]) 
print("Original arr:", arr) 
print("Shape : ", arr.shape) 
  
# deletion from 1D array 
object = 2
a = np.delete(arr, object) 
print("\ndeleteing the value at index {} from array:\n {}".format(object,a)) 
print("Shape : ", a.shape)

Original arr: [1 2 3 4 5]
Shape :  (5,)

deleteing the value at index 2 from array:
 [1 2 4 5]
Shape :  (4,)


In [30]:
# creating a numpy array 
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]) 
  
# printing array 
print("Array: " + str(array)) 
  
# reshaping numpy array 
# converting it to 2-D from 1-D array 
reshaped1 = array.reshape((4, array.size//4)) 
  
# printing reshaped array 
print("First Reshaped Array:") 
print(reshaped1) 
  
# creating another reshaped array 
reshaped2 = np.reshape(array, (2, 8)) 
  
# printing reshaped array 
print("\nSecond Reshaped Array:") 
print(reshaped2)

Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
First Reshaped Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Second Reshaped Array:
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [31]:
# Defining both the matrices 
a = np.array([5, 72, 13, 100]) 
b = np.array([2, 5, 10, 30]) 
  
# Performing addition using numpy function 
print("Addition:", np.add(a, b)) 
  
# Performing subtraction using numpy function 
print("Subtraction:", np.subtract(a, b)) 
  
# Performing multiplication using numpy function 
print("Multiplication:", np.multiply(a, b)) 
  
# Performing division using numpy functions 
print("Division:", np.divide(a, b)) 
  
# Performing mod on two matrices 
print("Mod:", np.mod(a, b)) 
  
#Performing remainder on two matrices 
print("Remainder:", np.remainder(a,b)) 
  
# Performing power of two matrices 
print("Power:", np.power(a, b)) 
  
# Performing Exponentiation 
print("Exponentiation:", np.exp(b))

Addition: [  7  77  23 130]
Subtraction: [ 3 67  3 70]
Multiplication: [  10  360  130 3000]
Division: [ 2.5        14.4         1.3         3.33333333]
Mod: [ 1  2  3 10]
Remainder: [ 1  2  3 10]
Power: [        25 1934917632  419538377          0]
Exponentiation: [7.38905610e+00 1.48413159e+02 2.20264658e+04 1.06864746e+13]


In [32]:
# 1D array 
arr = [20, 2, 7, 1, 34] 
  
# mean 
print("mean of arr:", np.mean(arr)) 
  
# median 
print("median of arr:", np.median(arr)) 
  
# sum 
print("Sum of arr(uint8):", np.sum(arr, dtype = np.uint8)) 
print("Sum of arr(float32):", np.sum(arr, dtype = np.float32)) 
  
# min and max 
print("maximum element:", np.max(arr)) 
print("minimum element:", np.min(arr)) 
  
# var 
print("var of arr:", np.var(arr)) 
print("var of arr(float32):", np.var(arr, dtype = np.float32)) 
  
# standard deviation 
print("std of arr:", np.std(arr)) 
print ("More precision with float32", np.std(arr, dtype = np.float32))

mean of arr: 12.8
median of arr: 7.0
Sum of arr(uint8): 64
Sum of arr(float32): 64.0
maximum element: 34
minimum element: 1
var of arr: 158.16
var of arr(float32): 158.16
std of arr: 12.576167937809991
More precision with float32 12.576168


In [33]:
# create numpy 1d-array 
array1 = np.array([0, 1, 2]) 
array2 = np.array([3, 4, 5]) 
  
# pearson product-moment correlation 
# coefficients of the arrays 
rslt = np.corrcoef(array1, array2) 
  
print(rslt)

[[1. 1.]
 [1. 1.]]
